name: Divine Designs
favicon: null
layout_spectrum: 0.6426305817440152
typography_spectrum: 0.7606847288552672
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.25797150330618024
  lightness: 0.31981511670164764
  saturation: 0.22652879217639565
  rhythmicContrast: 0.18452300457283854
purpose: []
